config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :posts, except: %i[index create] do
    member do
      put 'publish'
      put 'accept'
      put 'reject'
    end

    resources :reactions, only: %i[create update destroy]
    resources :comments, only: %i[create]
  end

  put '/save', to: 'posts#save', as: :autosave
  get '/readinglist', to: 'posts#readinglist', as: :readinglist

  resources :comments, only: %i[update destroy] do
    resources :replies, only: %i[create update destroy], controller: 'comments'
  end

  resources :tags, param: :name, only: %i[index show]

  namespace :dashboard do
    resources :tags
    resources :accounts, only: %i[index update]
    resources :posts, only: :index
  end

  namespace :settings do
    resources :profile, param: :username, only: %i[edit update]
    resources :password, param: :username, only: %i[edit update]
  end

  resources :users, param: :username, only: :show

  resources :notifications, only: :index

  resources :follows, only: %i[create destroy]

  resources :book_marks, only: %i[create destroy]

  mount ActionCable.server => '/cable'

  devise_for :users, path: '', controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  root 'home#index'
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  before_action :set_user

  def show
    @posts = @user.posts.accepted.includes(:tags)
    @comments = @user.comments
  end

  def update
    if @user.update(user_params)
      flash[:notice] = 'Your profile has been update'
      redirect_to edit_profile_path(@user.username)
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.required(:user).permit(:username, :email, :avatar)
  end

  def set_user
    @user = User.find_by(username: params[:username])
  end
end

app/controllers/settings/password_controller.rb
class Settings::PasswordController < ApplicationController
  before_action :set_user

  def edit
    authorize [:settings, @user]
  end

  def update
    authorize [:settings, @user]

    unless @user.valid_password?(params[:user][:old_password])
      @old_password_error = 'Password is not correct!'
      render 'edit'
      return
    end

    if @user.update(user_params)
      bypass_sign_in(@user)
      flash[:notice] = 'Your password has been change'
      redirect_to edit_settings_password_path(@user.username)
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.required(:user).permit(:password, :password_confirmation)
  end

  def set_user
    @user = User.find_by!(username: params[:username])
  end
end

app/controllers/settings/profile_controller.rb
class Settings::ProfileController < ApplicationController
  before_action :set_user

  def edit
    authorize [:settings, @user]
  end

  def update
    authorize [:settings, @user]

    if @user.update(user_params)
      flash[:notice] = 'Your profile has been update'
      redirect_to edit_settings_profile_path(@user.username)
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.required(:user).permit(:username, :email, :avatar)
  end

  def set_user
    @user = User.find_by!(username: params[:username])
  end
end

app/helpers/settings/password_helper.rb
module Settings::PasswordHelper
end

app/helpers/settings/profile_helper.rb
module Settings::ProfileHelper
end

app/views/settings/profile/edit.html.slim
- set_settings_meta_tag
= render "shared/navbar"

.container.p-0
  .col-9.mx-auto.justify-content-center
    .row.col-12.py-3
      h2.fw-bold
        | Settings for 
        = link_to current_user.username,
                  user_path(current_user.username),
                  class: "text-decoration-none"

    .row.justify-content-center.gx-3
      = render "settings/sidebar"

      .col-lg-9.col-md-10.col-sm-12.bg-white.border.rounded.p-4
        .h2.fw-bold
          | Update Profile 
        = form_with model: @user, url: settings_profile_path(current_user.username) do |f|
          .my-2
            = f.label :username
            = f.text_field :username,
                          class: "form-control"
            - if @user.errors.messages[:username].any?
                small.text-danger = @user.errors.messages[:username][0]

          .my-2
            = f.label :email
            = f.text_field :email,
                            class: "form-control"
            - if @user.errors.messages[:email].any?
                small.text-danger = @user.errors.messages[:email][0]

          .my-2
            .label
              | Profile image
            = image_tag @user.avatar,
                        size: "48x48",
                        class: "border rounded-circle object-fit-cover me-2"
            = f.file_field :avatar

          = f.submit "Save profile information", class: "btn btn-primary my-2 w-100"