config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :posts, except: %i[index create] do
    member do
      put 'publish'
      put 'accept'
      put 'reject'
    end

    resources :reactions, only: %i[create update destroy]
    resources :comments, only: %i[create]
  end

  put '/save', to: 'posts#save', as: :autosave
  get '/readinglist', to: 'posts#readinglist', as: :readinglist

  resources :comments, only: %i[update destroy] do
    resources :replies, only: %i[create update destroy], controller: 'comments'
  end

  resources :tags, param: :name, only: %i[index show]

  namespace :dashboard do
    resources :tags
    resources :accounts, only: %i[index update]
    resources :posts, only: :index
  end

  namespace :settings do
    resources :profile, param: :username, only: %i[edit update]
    resources :password, param: :username, only: %i[edit update]
  end

  resources :users, param: :username, only: :show

  resources :notifications, only: :index

  resources :follows, only: %i[create destroy]

  resources :book_marks, only: %i[create destroy]

  mount ActionCable.server => '/cable'

  devise_for :users, path: '', controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  root 'home#index'
end

app/controllers/reactions_controller.rb
class ReactionsController < ApplicationController
  before_action :set_post, only: %i[create update destroy]
  before_action :set_reaction, only: %i[update destroy]

  def create
    unless user_signed_in?
      flash.now[:alert] = 'You need to signin before react to a post.'
      return
    end

    if Reaction.reaction_types.include?(params[:reaction_type])
      @reaction = @post.reactions.build(user: current_user, reaction_type: params[:reaction_type])
    else
      redirect_to @post
      return
    end

    @reaction.save
    set_reactions

    Notifications::CreateNotificationService.call(@post.user, @reaction, 'reaction')
  end

  def update
    if Reaction.reaction_types.include?(params[:reaction_type]) &&
       @reaction.update(reaction_type: params[:reaction_type])
      set_reactions
    else
      redirect_to @post
    end
  end

  def destroy
    @reaction = @reaction.destroy.persisted?

    set_reactions
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def set_reaction
    @reaction = Reaction.find(params[:id])
  end

  def set_reactions
    @reactions = Reaction.where(post_id: params[:post_id])
  end
end

app/helpers/reactions_helper.rb
module ReactionsHelper
end

app/views/reactions/_post_reactions.html.slim
.post__option__reaction.btn-group.dropend.mb-3 title="Add reaction"
  .post__option__reaction__toggle type="button" data-bs-toggle="dropdown" aria-expanded="false"
    - if reaction
      = image_pack_tag "media/images/add-reaction-active-icon.svg", class: "mx-auto mb-2"
    - else 
      = image_pack_tag "media/images/add-reaction-icon.svg", class: "mx-auto mb-2"
    br
    span
      = reactions.size
  ul.post__option__reaction__menu.dropdown-menu.ms-2.px-3.rounded-5
    .d-flex.gap-1
      = render partial: "reactions/reaction_type", locals: { type: "like", reaction: reaction, icon_src: "media/images/like-icon.svg", count: reactions.select(&:like?).size, post: post }
      = render partial: "reactions/reaction_type", locals: { type: "unicorn", reaction: reaction, icon_src: "media/images/unicorn-icon.svg", count: reactions.select(&:unicorn?).size, post: post }
      = render partial: "reactions/reaction_type", locals: { type: "exploding_head", reaction: reaction, icon_src: "media/images/exploding_head-icon.svg", count: reactions.select(&:exploding_head?).size, post: post }
      = render partial: "reactions/reaction_type", locals: { type: "raised_hand", reaction: reaction, icon_src: "media/images/raised_hand-icon.svg", count: reactions.select(&:raised_hand?).size, post: post }
      = render partial: "reactions/reaction_type", locals: { type: "fire", reaction: reaction, icon_src: "media/images/fire-icon.svg", count: reactions.select(&:fire?).size, post: post }

app/views/reactions/_reaction_type.html.slim
- if reaction && reaction.reaction_type == type
  li class="text-center d-flex flex-column post__option__reaction__menu__item rounded-4 reaction-active"
    = link_to post_reaction_path(post, reaction), method: :delete, remote: true, class: "post__option__reaction__menu__item__link text-decoration-none text-reset p-2" do
      = image_pack_tag icon_src, size: "32x32", ariaHidden: "true"
      span
        = count
- else 
  li class="text-center d-flex flex-column post__option__reaction__menu__item rounded-4"
    - if reaction
      = link_to post_reaction_path(post, reaction, reaction_type: type), method: :put, remote: true, class: "post__option__reaction__menu__item__link text-decoration-none text-reset p-2" do 
        = image_pack_tag icon_src, size: "32x32", ariaHidden: "true"
        span
          = count
    - else 
      = link_to post_reactions_path(post, reaction_type: type), method: :post, remote: true, class: "post__option__reaction__menu__item__link text-decoration-none text-reset p-2" do 
        = image_pack_tag icon_src, size: "32x32", ariaHidden: "true"
        span
          = count
    

app/views/reactions/create.erb
$(".post__option__reation").replaceWith("<%= j render 'post_reactions', post: @post, reactions: @reactions, reaction: @reaction %>")

app/views/reactions/create.js.erb
<% if @reaction.present? %>
  $(".post__option__reaction").replaceWith("<%= j render 'post_reactions', post: @post, reactions: @reactions, reaction: @reaction %>")
  $(".post__main__reactions").replaceWith("<%= j render 'posts/reactions', post: @post %>")
<% end %>

<% if flash[:alert] %>
  $("body").append("<%= j display_alert(flash[:alert], 'danger') %>")

  setTimeout(function() {
    $(".alert").alert("close");
  }, 3500)
<% end %>

app/views/reactions/destroy.erb
$(".post__option__reation").replaceWith("<%= j render 'post_reactions', post: @post, reactions: @reactions, reaction: @reaction %>")

app/views/reactions/destroy.js.erb
$(".post__option__reaction").replaceWith("<%= j render 'post_reactions', post: @post, reactions: @reactions, reaction: @reaction %>")
$(".post__main__reactions").replaceWith("<%= j render 'posts/reactions', post: @post %>")

app/views/reactions/update.erb
$(".post__option__reation").replaceWith("<%= j render 'post_reactions', post: @post, reactions: @reactions, reaction: @reaction %>")

app/views/reactions/update.js.erb
$(".post__option__reaction").replaceWith("<%= j render 'post_reactions', post: @post, reactions: @reactions, reaction: @reaction %>")
$(".post__main__reactions").replaceWith("<%= j render 'posts/reactions', post: @post %>")