config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :posts, except: %i[index create] do
    member do
      put 'publish'
      put 'accept'
      put 'reject'
    end

    resources :reactions, only: %i[create update destroy]
    resources :comments, only: %i[create]
  end

  put '/save', to: 'posts#save', as: :autosave
  get '/readinglist', to: 'posts#readinglist', as: :readinglist

  resources :comments, only: %i[update destroy] do
    resources :replies, only: %i[create update destroy], controller: 'comments'
  end

  resources :tags, param: :name, only: %i[index show]

  namespace :dashboard do
    resources :tags
    resources :accounts, only: %i[index update]
    resources :posts, only: :index
  end

  namespace :settings do
    resources :profile, param: :username, only: %i[edit update]
    resources :password, param: :username, only: %i[edit update]
  end

  resources :users, param: :username, only: :show

  resources :notifications, only: :index

  resources :follows, only: %i[create destroy]

  resources :book_marks, only: %i[create destroy]

  mount ActionCable.server => '/cable'

  devise_for :users, path: '', controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  root 'home#index'
end

app/views/shared/_list_posts.html.slim
- posts.each_with_index do |post, index|
  = turbo_frame_tag dom_id(post)
    .mb-2.pb-2.bg-white.border.rounded.shadow-sm  data-controller="posts"
      - if post.pending?
        .px-4.pt-2.text-warning
          | Pending
      - if post.rejected?
        .px-4.pt-2.text-danger
          | Rejected
      = cover_image_if_first_post(page, post, index == 0)
      .py-2.px-4
        .fs-6.text-secondary
          = link_to user_path(post.user.username), data: { turbo_frame: :_top }, class: "text-decoration-none text-secondary" do
            = render partial: "shared/post_username_link", locals: { post: post }
          - if policy(post).destroy?
            = render "shared/post_action", post: post
        small.text-secondary
          = post.created_at.to_date.to_fs(:long)
      .pb-2.px-4
        = link_to post.title, post, data: { turbo_frame: :_top }, class: "fs-2 text-black fw-bold text-decoration-none"
      .pb-2.px-4
        = render partial: "shared/post_tags_link", locals: { post: post }
      .pb-2.px-3
        - if post.reactions.present?
          = link_to post, data: { turbo_frame: :_top }, class: "text-decoration-none text-reset menu-link py-2 px-2 rounded" do
            = render "shared/reactions",
                    icon_src: "media/images/like-icon.svg",
                    count: post.reactions.select(&:like?).size
            = render "shared/reactions",
                    icon_src: "media/images/unicorn-icon.svg",
                    count: post.reactions.select(&:unicorn?).size
            = render "shared/reactions",
                    icon_src: "media/images/exploding_head-icon.svg",
                    count: post.reactions.select(&:exploding_head?).size
            = render "shared/reactions",
                    icon_src: "media/images/raised_hand-icon.svg",
                    count: post.reactions.select(&:raised_hand?).size
            = render "shared/reactions",
                    icon_src: "media/images/fire-icon.svg",
                    count: post.reactions.select(&:fire?).size
            small.ms-1.align-bottom
              = post.reactions.size
              |  Reactions 
        = link_to post_path(post) + "#comments", data: { turbo_frame: :_top }, class: "text-decoration-none text-reset menu-link py-2 px-2 rounded" do
          = image_pack_tag "media/images/comment-icon.svg", size: "20x20"
          small.ms-1.align-bottom
            - if post.comments.size > 0
              = post.comments_count
              |  Comments
            - else 
              | Add comments
.p-0 id="load-more"

app/views/shared/_navbar.html.slim
.offcanvas.offcanvas-start tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel"
  .offcanvas-header
    .offcanvas-title id="offcanvasExampleLabel"
      h5.fw-bold Blog Community
    button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"
  .offcanvas-body.py-0
    = render "shared/side_menu"
.bg-white.shadown-sm
  .container.p-0
    nav.navbar.navbar-expand-lg.navbar-expand-md.navbar-light.mx-auto.py-2.px-2.px-md-0
      .container-fluid.gx-0
        .navbar.navbar-expand-md
          .navbar.p-0.ms-1.me-3.side_navbar_toggle
            button.navbar-toggler.p-0.border-0 type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasExample" aria-controls="offcanvasExample"
              span.navbar-toggler-icon
          = link_to "BLOG", root_path, class: "navbar-brand fw-bold text-white bg-dark px-2 rounded ms-0"
        .collapse.navbar-collapse
          = form_with url: root_path, method: :get, class: "d-flex position-relative w-40" do
            = text_field_tag :search, params[:search], placeholder: "Search..." , class: "form-control"
            button.btn.text-secondary.border-0.position-absolute.end-0.h-100 type="submit"
              i.fa.fa-search
        .navbar.justify-content-end
          - if current_user 
            = link_to "Create Post", new_post_path, class: "btn btn-outline-primary me-3"
            = link_to notifications_path, class: "position-relative" do
              i class="fa-regular fa-bell fa-lg btn-outline-primary p-2 rounded btn border-0"
              small.position-absolute.end-0.top-0.bg-danger.rounded.py-0.px-1.text-white id="unview-notifications-count"
                - if @unviewed_notifications_count > 0
                  = @unviewed_notifications_count
            .dropdown.ms-3
              div type="button" data-bs-toggle="dropdown" aria-expanded="false"
                = image_tag current_user.avatar,
                            size: "40x40",
                            class: "rounded-circle border object-fit-cover"
              ul class="dropdown-menu dropdown-menu-end"
                li
                  = link_to current_user.username, user_path(current_user.username), class: "dropdown-item"
                li 
                  hr class="dropdown-divider"
                li 
                  = link_to "Dashboard", dashboard_posts_path, class: "dropdown-item"
                li 
                  = link_to "Reading list", readinglist_path, class: "dropdown-item"
                li 
                  = link_to "Settings", edit_settings_profile_path(current_user.username), class: "dropdown-item"
                li 
                  hr class="dropdown-divider"
                li 
                  = link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item"
          - else
            = link_to "Log in", new_user_session_path, class: "btn btn-outline-primary mx-3"
            = link_to "Sign up", new_user_registration_path, class: "btn btn-outline-primary"

app/views/shared/_post_action.html.slim
span.dropdown.text-secondary.float-end
  span type="button" data-bs-toggle="dropdown" aria-expanded="false"
    = image_pack_tag "media/images/option-icon.svg"
  ul class="dropdown-menu dropdown-menu-end"
    - if policy(post).update?
      = edit_post_link post
    - if policy(post).destroy?
      = link_to "Delete", post, method: :delete, data: { confirm: "Are you sure to delete this post?" }, class: "menu-link text-decoration-none dropdown-item"

app/views/shared/_post_tags_link.html.slim
- post.tags.each do |tag|
  = link_to tag_path(tag.name), data: { turbo_frame: :_top }, class: "p-2 rounded text-reset text-decoration-none btn-negative" do 
    | #
    = tag.name

app/views/shared/_post_username_link.html.slim
= image_tag post.user.avatar,
            size: "32x32",
            class: "rounded-circle border me-1 object-fit-cover"
= post.user.username

app/views/shared/_reactions.html.slim
- if count > 0
  = image_pack_tag icon_src, size: "20x20"

app/views/shared/_side_menu.html.slim
= link_to root_path, class: "btn menu-link border-0 w-100 text-start mb-3 p-0" do
  = image_pack_tag "media/images/home-icon.svg", class: "pe-2" 
  | Home

= link_to tags_path, class: "btn menu-link border-0 w-100 text-start mb-1 p-0" do
  = image_pack_tag "media/images/tags-icon.svg", class: "pe-2"
  | Tags

app/views/shared/page_not_found.html.slim
= render "shared/navbar"

.mx-auto.text-center.p-3
  h1 Page Not Found!
  h1.p-5.text-primary.error_404_text 404
  p.fs-4 The page you were looking for doesn't exists.
  = link_to "Go to Home Page", root_path, class: "text-primary fs-5"