config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :posts, except: %i[index create] do
    member do
      put 'publish'
      put 'accept'
      put 'reject'
    end

    resources :reactions, only: %i[create update destroy]
    resources :comments, only: %i[create]
  end

  put '/save', to: 'posts#save', as: :autosave
  get '/readinglist', to: 'posts#readinglist', as: :readinglist

  resources :comments, only: %i[update destroy] do
    resources :replies, only: %i[create update destroy], controller: 'comments'
  end

  resources :tags, param: :name, only: %i[index show]

  namespace :dashboard do
    resources :tags
    resources :accounts, only: %i[index update]
    resources :posts, only: :index
  end

  namespace :settings do
    resources :profile, param: :username, only: %i[edit update]
    resources :password, param: :username, only: %i[edit update]
  end

  resources :users, param: :username, only: :show

  resources :notifications, only: :index

  resources :follows, only: %i[create destroy]

  resources :book_marks, only: %i[create destroy]

  mount ActionCable.server => '/cable'

  devise_for :users, path: '', controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  root 'home#index'
end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id   :bigint           not null, primary key
#  name :string
#
class Tag < ApplicationRecord
  has_many :post_tags, dependent: :destroy
  has_many :posts, through: :post_tags

  validates :name, presence: { message: 'Enter tag name!' }, uniqueness: { message: 'Tag already exist!' }
end

app/controllers/dashboard/accounts_controller.rb
class Dashboard::AccountsController < ApplicationController
  before_action :set_account, except: %i[index]

  before_action :authenticate_user!

  def index
    @accounts = policy_scope([:dashboard, User]).all.order(status: :desc, role: :desc, id: :asc)
    @accounts = Accounts::AccountsFilterService.call(@accounts, params)
    @accounts_count = @accounts.size

    @pagy, @accounts = pagy(@accounts, items: 10)

    if request.xhr? && params[:next_page] == 'true'
      respond_to do |format|
        format.js { render 'next_page' }
      end
    end
  end

  def update
    authorize [:dashboard, @account]

    @account.update(role: params[:role]) if User.roles.include?(params[:role])
    @account.update(status: params[:status]) if User.statuses.include?(params[:status])
  end

  private

  def set_account
    @account = User.find(params[:id])
  end
end

app/controllers/dashboard/posts_controller.rb
class Dashboard::PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @posts = if current_user.admin?
               Post.all
                   .order(created_at: :desc)
                   .includes({ user: { avatar_attachment: :blob } }, :tags, :reactions)
             else
               current_user.posts
                           .order(created_at: :desc)
                           .includes(%i[tags reactions])
             end

    @posts = @posts.where.not(status: :drafting)
    @posts = Posts::ListPostsService.call(@posts, params)

    @posts_count = @posts.count

    @pagy, @posts = pagy(@posts)
  end
end

app/controllers/dashboard/tags_controller.rb
class Dashboard::TagsController < ApplicationController
  before_action :set_tag, only: %i[update destroy]

  before_action :authenticate_user!

  def index
    @tags = policy_scope([:dashboard, Tag]).all.order(id: :desc)
    @new_tag = Tag.new
  end

  def create
    @new_tag = Tag.new(tag_params)
    authorize [:dashboard, @new_tag]
    @new_tag.save
  end

  def update
    authorize [:dashboard, @tag]
    @tag.update(tag_params)
  end

  def destroy
    authorize [:dashboard, @tag]
    @tag.destroy
  end

  private

  def tag_params
    params.required(:tag).permit(:name)
  end

  def set_tag
    @tag = Tag.find(params[:id])
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all.order(id: :asc)

    @tags = @tags.where('name LIKE ?', "%#{params[:search_tags]}%") if params[:search_tags].present?
  end

  def show
    @tag = Tag.find_by!(name: params[:name])
    @posts = @tag.posts.accepted.includes({ user: { avatar_attachment: :blob } }, :tags, :reactions)
    @posts = Posts::ListPostsService.call(@posts, params, current_user)

    @users = User.joins(posts: :tags)
                 .where(tags: { id: @tag.id }, posts: { status: :accepted })
                 .group('users.id')
                 .order('count(posts.id) DESC')
                 .limit(16)
                 .with_attached_avatar

    @pagy, @posts = pagy(@posts)
  end
end

app/helpers/dashboard/accounts_helper.rb
module Dashboard::AccountsHelper
  def display_status(account)
    if account.banned?
      content_tag(:div, 'Banned', class: 'text-danger ')
    else
      content_tag(:div, 'Active', class: 'text-success')
    end
  end

  def display_role(account)
    content_tag(:div, 'Admin', class: 'text-primary') if account.admin?
  end
end

app/helpers/dashboard/dashboard_helper.rb
module Dashboard::DashboardHelper
  def sidebar_tags
    if controller_name == 'tags'
      content_tag(:span,
                  class: 'btn menu-link border-0 text-start text-decoration-none text-reset bg-white d-flex') do
        concat('Tags')
        concat(content_tag(:span,
                           @tags.size,
                           class: 'dashboard__body__sidebar__tags__count rounded ms-auto px-1'))
      end
    else
      link_to 'Tags',
              dashboard_tags_path,
              class: 'btn menu-link border-0 text-start text-decoration-none text-reset d-flex'
    end
  end

  def sidebar_accounts
    if controller_name == 'accounts'
      content_tag(:span,
                  class: 'btn menu-link border-0 text-start text-decoration-none text-reset bg-white d-flex') do
        concat('Accounts')
        concat(content_tag(:span,
                           @accounts_count,
                           class: 'dashboard__body__sidebar__tags__count rounded ms-auto px-1'))
      end
    else
      link_to 'Accounts',
              dashboard_accounts_path,
              class: 'btn menu-link border-0 text-start text-decoration-none text-reset d-flex'
    end
  end
end

app/helpers/dashboard/posts_helper.rb
module Dashboard::PostsHelper
end

app/helpers/dashboard/tags_helper.rb
module Dashboard::TagsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/dashboard/tags/_tag.html.slim
.dashboard__body__table__tag__detail.bg-white.border-bottom.p-4.row id="dashboard-tag-#{tag.id}" data-controller="dashboard-tags"
  .col-lg-6.col-md-5.col-sm-6.dashboard__body__table__tag__detail__name
    .fs-5.mb-1.fw-bold.text-secondary-alter data-dashboard-tags-target="tagName"
      = tag.name

    = form_with model: tag, url: dashboard_tag_path(tag), local: false, class: "d-none", data: { dashboard_tags_target: "editForm" } do |f|
      = f.text_field :name, class: "fs-5 fw-bold text-secondary-alter w-50 me-1 tag-name-input"
      small.text-danger id="dashboard-tag-#{tag.id}-error"
      .mt-1
        = f.submit "Save", class: "btn btn-negative py-0 px-1"
        .btn.btn-negative.py-0.px-1 data-action="click->dashboard-tags#toggleEdit"
          | Dissmis

  .dashboard__body__table__tag__detail__posts-count.col-lg-3.col-md-3.col-sm-2.py-2
    | Posts: 
    = tag.posts_count || 0
    
  .dashboard__body__table__tag__detail__option.col-lg-3.col-md-2.col-sm-2
    .d-flex
      button.dashboard__body__table__tag__detail__option__edit.btn.btn-outline-secondary.ms-auto.me-2 data-dashboard-tags-target="toggleEditButton" data-action="dashboard-tags#toggleEdit"
        | Edit
      = link_to "Delete", dashboard_tag_path(tag), method: :delete, remote: true, class: "btn btn-outline-secondary", data: {confirm: 'Are you sure to delete this tag?'}

app/views/dashboard/tags/create.js.erb
<% if @new_tag.valid? %>
  $(".dashboard__body__table__tag").prepend("<%= j render 'tag', tag: @new_tag %>")
  $(".dashboard__body__sidebar__tags__count")[0].innerHTML = +$(".dashboard__body__sidebar__tags__count")[0].innerHTML + 1
  $(".dashboard__body__table__add-form").addClass("d-none")
  $(".dashboard__body__table__add-button").removeClass("d-none")
  $(".dashboard__body__table__add-form input").val("")
<% else %>
  $(".dashboard__body__table__add-form__error")[0].innerHTML = "<%= @new_tag.errors.messages[:name][0] %>"
<% end %>

app/views/dashboard/tags/destroy.js.erb
$("#dashboard-tag-<%= @tag.id %>").remove()
$(".dashboard__body__sidebar__tags__count")[0].innerHTML = +$(".dashboard__body__sidebar__tags__count")[0].innerHTML - 1

app/views/dashboard/tags/index.html.slim
- set_dashboard_meta_tags
= render "shared/navbar"

.container.p-0
  .mx-auto.justify-content-center
    .dashboard.row.col-12.py-3.px-sm-0.px-3
      h3.dashboard__head.fw-bold
        | Dashboard >> Tags
    
    .container
      .row.dashboard__body.justify-content-center
        = render "dashboard/sidebar"

        .dashboard__body__table.col-lg-10.col-md-9.col-sm-12.p-0.ps-md-3.ps-0 data-controller="dashboard-tags"
          .dashboard__body__table__add-button.btn.btn-positive.py-1.mx-sm-0.mx-3.fw-bold data-dashboard-tags-target="toggleAddButton" data-action="click->dashboard-tags#toggleAdd"
            | Add +
          = form_with model: @new_tag, url: dashboard_tags_path, local: false, class: "dashboard__body__table__add-form d-none", data: { dashboard_tags_target: "addForm" } do |f|
            = f.text_field :name, class: "fs-5 fw-bold text-secondary-alter w-50 me-1 tag-name-input"
            = f.submit "Save", class: "btn btn-positive py-1"
            .btn.btn-negative.bg-transparent data-action="click->dashboard-tags#toggleAdd"
              | Dissmis
            .dashboard__body__table__add-form__error.text-danger

          .dashboard__body__table__tag.container.shadow-sm.rounded.mt-2
            - @tags.each do |tag|
              = render "tag", tag: tag

app/views/dashboard/tags/update.js.erb
<% if @tag.valid? %>
  $("#dashboard-tag-<%= @tag.id %>").replaceWith("<%= j render 'tag', tag: @tag %>")
<% else %>
  $("#dashboard-tag-<%= @tag.id %>-error")[0].innerHTML = "<%= @tag.errors.messages[:name][0] %>"
<% end %>